#
# ███████╗███████╗███████╗██╗  ██╗     ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ 
# ██╔════╝██╔════╝██╔════╝██║  ██║    ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ 
# ███████╗█████╗  ███████╗███████║    ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
# ╚════██║██╔══╝  ╚════██║██╔══██║    ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
# ███████║███████╗███████║██║  ██║    ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
# ╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ 
#
# Smart session manager for the terminal
# https://github.com/joshmedeski/sesh

sort_order = ["tmux", "config", "tmuxinator", "zoxide"]

[default_session]
startup_command = "yy"
startup_command_ignore_dirs = ["~/repos", "~/.config"]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "go-pocket"
path = "~/learn/go/learngo-pocket/"
startup_command = "~/.config/sesh/scripts/devenv.sh"

[[session]]
name = "downloads"
path = "~/Downloads/"
startup_command = "yy"

[[session]]
name = "learn"
path = "~/learn/"
startup_command = "yy"

[[session]]
name = "go-gallery"
path = "~/learn/go/go-gallery/"
startup_command = "~/.config/sesh/scripts/devenv.sh"

[[session]]
name = "go-playground"
path = "~/learn/go/playground/"
startup_command = "~/.config/sesh/scripts/devenv.sh"

[[session]]
name = "solid-mp3"
path = "~/learn/_projects/solid-mp3"
startup_command = "~/.config/sesh/scripts/devenv.sh"

[[session]]
name = "learn odin"
path = "~/learn/odin/"
startup_command = "~/.config/sesh/scripts/devenv.sh"
